### ISSUE TITLE
Ошибка при запуске локального сервера npm run dev

### ISSUE THREAD

**Issue by AleksandrDyatlov** [mrlss/generator-scaffolder#136]
**Получаю такую ошибку при запуске, до этого момента все гладко прошло**

```
Error: ENOENT: no such file or directory, scandir 'D:\Webpack-test\markup/D:\Webpack-test\markup/src/views'
    at readdirSync (fs.js:790:3)
    at generateHtmlPlugins (D:\Webpack-test\markup\webpack.config.js:144:25)
    at Object.<anonymous> (D:\Webpack-test\markup\webpack.config.js:182:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at WEBPACK_OPTIONS (D:\Webpack-test\markup\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (D:\Webpack-test\markup\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at D:\Webpack-test\markup\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Webpack-test\markup\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (D:\Webpack-test\markup\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! p2h-webpack@2.0.8 dev: `rimraf dist && cross-env NODE_ENV=development webpack-dev-server --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p2h-webpack@2.0.8 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mrlss** [comment]
Fixed, thanks for the issue :)
